# Generated by Django 6.1.2 on 2026-10-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'key'], name='planner_pla_state_386e94_idx')],
            },
        ),
    ]
